# Generated by Django 5.1.3 on 2024-11-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('PDF', 'Document PDF'), ('VIDEO', 'Vidéo')], max_length=5)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='formations/')),
                ('lien_video', models.URLField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
