# Generated by Django 5.1.3 on 2024-11-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='lien_video',
            field=models.CharField(max_length=200),
        ),
    ]
