# Generated by Django 5.1.3 on 2024-11-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_alter_formation_lien_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='lien_video',
        ),
    ]
